// Týmové fotky — chronologie mužstev, přepsaná z v0 (`afkbratcice.cz/tymove_fotky`).
//
// **Data, ne uu5String:** stránka je 35× totéž (nadpis, fotka, jmenné řady), takže text
// drží tenhle seznam a značky z něj skládá `content/pages.js`. Je to zároveň tvar, který
// půjde jednou beze změny do ECC sekcí.
//
// Fotky leží v `client/public/assets/teams/` a jedou ze statiky, ne z GCS (frontend.md
// počítal s kolekcí `page` v BinaryStore). Důvod: obsah téhle stránky je natvrdo v kódu,
// takže i obrázky mají cestovat s buildem — jinak by odkazy mířily do dev bucketu, který
// v produkci neexistuje. Až obsah přejde do ECC, přejdou s ním.
//
// Jsou to náhledy z v0 (600 px), ne originály — ty mají přes 5 MB kus. I tak jich je
// 7,5 MB dohromady, protože jsou uložené neúsporně; čekají na převod do webp
// (todo.md, 5.5). Proto `loading="lazy"` u každé.

const TEAM_PHOTOS = [
  { season: "1943/1944", team: "Muži", file: "1943-1944_men.jpg", rowList: [{ label: "Horní řada zleva", names: "Jiří Prášek, Josef Vavřina, Jaroslav Miláček, Oldřich Vavřina, Josef Říha, Stanislav Hamza, Hendl (trenér), Vladimír Ryšavý" }, { label: "Dolní řada zleva", names: "Karel Volenec, Bedřich Novotný, Václav Štěpánek" }] },
  { season: "1947/1948", team: "Muži", file: "1947-1948_men.jpg", rowList: [{ label: "Horní řada zleva", names: "Jiří Prášek, Knický, Josef Ságl, Oldřich Vavřina, Jaroslav Miláček, Václav Štěpánek, Josef Říha, Alois Štěpánek" }, { label: "Dolní řada zleva", names: "Antonín Čapek, Bedřich Novotný, Václav Havránek" }] },
  { season: "1956/1957", team: "Muži", file: "1956-1957_men.jpg", rowList: [{ label: "Horní řada zleva", names: "Jaroslav Pecina, Josef Miláček, Miroslav Dvořák (Baxa), Miroslav Daněk, Zdeněk Dalešický, Miloš Čech" }, { label: "Dolní řada zleva", names: "Milan Vaňkát, Václav Čech, Václav Rak, Jiří Rak, Miloslav Ronovský" }] },
  { season: "1969/1970", team: "Muži", file: "1969-1970_men.jpg", rowList: [{ label: "Horní řada zleva", names: "Josef Ságl (trenér), Václav Prášek, Milan Piskač, Bohumil Štěpánek, Václav Pipek, Jiří Sklenář, Miroslav Prášek, Jaroslav Miláček (trenér)" }, { label: "Dolní řada zleva", names: "Jarmil Ronovský, Karel Hazuka, Josef Krejčík, Zdeněk Novotný, Josef Profous" }] },
  { season: "1970/1971", team: "Muži", file: "1970-1971_men.jpg", rowList: [{ label: "Horní řada zleva", names: "Jiří Sklenář, Václav Prášek, Josef Ságl (trenér), Bohumil Štěpánek, Miroslav Prášek, Karel Hazuka, Václav Pipek, Jaroslav Miláček (trenér)" }, { label: "Dolní řada zleva", names: "Josef Ašenbrener, Josef Semerád, Zdeněk Novotný, Josef Krejčík, Stanislav Rada, Josef Bucek" }] },
  { season: "1976/1977", team: "Muži", file: "1976-1977_men.jpg", rowList: [{ label: "Horní řada zleva", names: "Miloslav Ronovský, Josef Krejčík, Josef Pipek, Jiří Sklenář, Václav Ryšavý, Bohumil Štěpánek, Miloslav Marušák, Josef Javůrek" }, { label: "Dolní řada zleva", names: "Josef Profous, Josef Bak, Zdeněk Novotný, Karel Hazuka, Václav Ronovský" }] },
  { season: "1977/1978", team: "Muži", file: "1977-1978_men.jpg", note: "28. 5. 1978 - mistrovský zápas AFK Bratčice - ČSSS Kluky 3:1. Postup do II. třídy - okresní přebor.", rowList: [{ label: "Horní řada zleva", names: "Josef Ságl (trenér), Vladimír Prášek, Josef Zábojník, Václav Pipek, Jaroslav Zajíc, Jan Janouškovec, Miroslav Prášek, Josef Pipek, Alois Hrabaň, Zdeněk Novotný" }, { label: "Dolní řada zleva", names: "Josef Ságl ml., Jan Jeřábek, Vladimír Kupera, Bedřich Vágner, Květoslav Vršovský, Milan Zajíc, Václav Prášek" }] },
  { season: "1979/1980", team: "Muži", file: "1979-1980_men.jpg", rowList: [{ label: "Horní řada zleva", names: "Jaroslav Zajíc, Josef Bucek, Miloslav Ronovský, Václav Pipek, Václav Prášek, Alois Hrabaň, Zdeněk Novotný (trenér)" }, { label: "Dolní řada zleva", names: "Vladimír Kupera, Josef Ságl, Václav Novotný, Václav Říha, Květoslav Vršovský" }] },
  { season: "1980/1981", team: "Žáci", file: "1980-1981_children.jpg", note: "Přeborník okresu Kutná Hora", rowList: [{ label: "Horní řada zleva", names: "Miroslav Malík, Petr Kořínek, Josef Fanta, Radek Ledvinka, Václav Čech, Václav Ronovský (trenér)" }, { label: "Prostřední řada zleva", names: "Jaroslav Doležal, Jaroslav Kotrba, Josef Moravec, Josef Havránek, Martin Milaberský, Miloslav Ronovský, Vladislav Kořínek, Pavel Havránek" }, { label: "Dolní řada zleva", names: "Jindřich Žaloudek" }] },
  { season: "1981/1982", team: "Muži", file: "1981-1982_men.jpg", rowList: [{ label: "Horní řada zleva", names: "Vladimír Kupera, Josef Ságl, Antonín Čapek, Luboš Říha, Václav Pipek, Václav Prášek" }, { label: "Dolní řada zleva", names: "Jaroslav Roth, Jaroslav Zajíc, Jan Jeřábek, Pavel Bak, Milan Dalešický" }] },
  { season: "1988/1989", team: "Stará garda", file: "1988-1989_old.jpg", rowList: [{ label: "Horní řada zleva", names: "Miloslav Ronovský, Václav Ryšavý, Josef Kotrba, Čeněk Chleborád, Václav Novotný, Václav Pavlas, Josef Štěpánek" }, { label: "Dolní řada zleva", names: "Zdeněk Novotný, Jindřich Ronovský, Josef Profous, Ladislav Chvátal" }] },
  { season: "1990/1991", team: "Žáci", file: "1990-1991_children.jpg", rowList: [{ label: "Horní řada zleva", names: "Tomáš Říha, Roman Prášek, Tomáš Hazuka, Radek Čejka" }, { label: "Prostřední řada zleva", names: "Václav Ronovský ml., Vladimír Kupera ml., Aleš Kotrba, Pavel Klement, Lukáš Zajíc" }, { label: "Dolní řada zleva", names: "Radim Čejka" }] },
  { season: "1994/1995", team: "Žáci", file: "1994-1995_children.jpg", rowList: [{ label: "Horní řada zleva", names: "Vladimír Kupera (trenér), Karel Čubr, Václav Ronovský, Radek Kruml, Roman Prášek, Jan Štajner, Dobroslav Šaroun, Lukáš Zajíc, Miroslav Prášek (trenér)" }, { label: "Dolní řada zleva", names: "Radek Prášek, Jakub Ronovský, Michal Dušek, Martin Vondráček, Vladimír Kupera ml., Jan Krejza, Miloslav Chvátal" }] },
  { season: "1998/1999", team: "Muži", file: "1998-1999_men.jpg", rowList: [{ label: "Horní řada zleva", names: "Josef Ságl (trenér), Lukáš Říha, Bohumil Čapek, Josef Volenec, Vladimír Kupera ml., Jaroslav Doležal, Milan Dalešický, Aleš Kotrba" }, { label: "Dolní řada zleva", names: "Pavel Klement, David Říha, Václav Ronovský ml., Pavel Bak, Zdeněk Novotný" }, { label: "Horní řada zleva", names: "David Vondráček, Václav Říha, Zdeněk Musil, Jan Krejza, Ondřej Čapek, Petr Doležal (trenér)" }, { label: "Dolní řada zleva", names: "Tomáš Kodeš, Tomáš Semrád, Jan Vaněk, Tomáš Doležal, David Semrád" }] },
  { season: "1999/2000", team: "Muži", file: "1999-2000_men.jpg", rowList: [{ label: "Horní řada zleva", names: "Josef Kotrba, Josef Ságl (trenér), Roman Hnilička, Roman Popelka, Vladimír Kupera ml., Petr Kaňka, Václav Ronovský ml., Bohumil Čapek, Karel Čubr, Pavel Klement, Jaroslav Doležal, Josef Bak, Václav Ronovský" }, { label: "Dolní řada zleva", names: "Lukáš Říha, Pavel Bak, Josef Volenec, Milan Dalešický, Jindřich Žaloudek, David Říha, Zdeněk Novotný, Aleš Kotrba, Josef Paták" }] },
  { season: "2000/2001", team: "Žáci", file: "2000-2001_children.jpg", rowList: [{ label: "Horní řada zleva", names: "Petr Marousek, Radek Kalina, David Vondráček, Luboš Říha, Martin Černovský, Jan Krejza, Václav Říha, Zdeněk Musil, Petr Doležal (trenér)" }, { label: "Dolní řada zleva", names: "Ondřej Čapek, Zdeněk Šaroun, Tomáš Doležal, Tomáš Kalina, David Semrád, Tomáš Semrád" }] },
  { season: "2002/2003", team: "Muži", file: "2002-2003_men.jpg", rowList: [{ label: "Horní řada zleva", names: "Jaroslav Doležal, Václav Ronovský, Ilona Kotrbová, Aleš Kotrba" }, { label: "Prostřední řada zleva", names: "Jakub Ronovský, Pavel Klement, Petr Kaňka" }, { label: "Dolní řada zleva", names: "Martin Karlovský" }] },
  { season: "2004/2005", team: "Stará garda", file: "2004-2005_1_old.jpg", rowList: [{ label: "Horní řada zleva", names: "Vladimír Prášek, Miroslav Malík, Josef Volenec, Antonín Čapek, Karel Šindelka, Jaroslav Doležal, Vlastimil Havránek, Karel Milaberský, Jaroslav Makiš, Václav Hrabaň, Josef Pipek" }, { label: "Dolní řada zleva", names: "Jaroslav Roth, Vladimír Kupera, Jaroslav Kotrba, Luboš Říha, Jindřich Žaloudek" }, { label: "Horní řada zleva", names: "Miloslav Ronovský (trenér), Vlastimil Poklop, Vlastimil Havránek, Jaroslav Doležal, Jaroslav Makiš, Vlastimil Miláček, Miroslav Prášek, Jaroslav Roth" }, { label: "Prostřední řada zleva", names: "Josef Klaus, Václav Prášek, Luboš Říha, Karel Šindelka, Josef Ságl, Vladimír Kupera, Josef Volenec" }, { label: "Dolní řada zleva", names: "Petr Dostál" }, { label: "Horní řada zleva", names: "Adam Sardel, Zdeněk Šaroun, Tomáš Doležal, Radek Novotný, Petra Čapková" }, { label: "Prostřední řada zleva", names: "Martin Kaňka, Filip Machka, Aleš Zelený, Josef Mrkvička, Libor Milaberský, Vladimír Kořínek, Jan Čapek" }, { label: "Dolní řada zleva", names: "Jan Kropáček" }] },
  { season: "2005/2006", team: "Stará garda", file: "2005-2006_old.jpg", rowList: [{ label: "Horní řada zleva", names: "Václav Ronovský (trenér), Bohumil Čapek, Václav Pipek, Vladimír Prášek, Stanislav Kepr, Jaroslav Doležal, Václav Hrabaň, Antonín Čapek, Miroslav Prášek, Zdeněk Piška" }, { label: "Prostřední řada zleva", names: "Kamil Havelka, Jaroslav Roth, Václav Prášek, Luboš Říha, Vladimír Kupera, Vlastimil Havránek" }, { label: "Dolní řada zleva", names: "Petr Dostál" }] },
  { season: "2007/2008", team: "Stará garda", file: "2007-2008_old.jpg", rowList: [{ label: "Horní řada zleva", names: "Vladimír Prášek, Václav Pipek, Jaroslav Roth, Josef Klaus, Zdeněk Piška, Vlastimil Miláček, Karel Šindelka, Antonín Čapek, Václav Prášek" }, { label: "Prostřední řada zleva", names: "Vladimír Kupera, Jaroslav Kotrba, Luboš Říha, Kamil Havelka, Josef Volenec" }, { label: "Dolní řada zleva", names: "Petr Dostál" }, { label: "Horní řada zleva", names: "Josef Mařica (trenér), Luboš Kruml, Michal Koudelka, Zdeněk Šaroun, Jan Čapek, David Semrád, Radek Novotný, Tomáš Doležal, Robert Uhlíř" }, { label: "Dolní řada zleva", names: "Libor Mysliveček, Pavel Havránek, Lukáš Smutný, Vladislav Kořínek, Libor Milaberský, Jan Vaněk, Ondřej Čapek" }] },
  { season: "2010/2011", team: "Muži", file: "2010-2011_men.jpg", rowList: [{ label: "Horní řada zleva", names: "Jaroslav Doležal (trenér), Jakub Ronovský, Jan Čapek, Milan Urválek, Vladimír Kupera, Aleš Šulc, Radek Prášek, Václav Říha, Václav Ronovský ml., Václav Ronovský (předseda)" }, { label: "Dolní řada zleva", names: "Zuzana Piskačová, Lukáš Dvořák, Zdeněk Novotný, Jan Vaněk, Petr Dostál, David Míchal, Ondřej Čapek, Robert Uhlíř, Vlastimil Růžička" }] },
  { season: "2011/2012", team: "Muži", file: "2011-2012_men.jpg", rowList: [{ label: "Horní řada zleva", names: "Jakub Ronovský, Václav Ronovský, Jaroslav Doležal (trenér), Marián Hodač, Václav Říha, Martin Kaňka, Aleš Šulc, Robert Uhlíř, Radek Prášek, Bohumil Čapek, Luboš Říha" }, { label: "Prostřední řada zleva", names: "Zdeněk Novotný, Milan Urválek, Lukáš Dvořák, Ondřej Čapek, Radek Beneš, Vlastimil Růžička" }, { label: "Dolní řada zleva", names: "David Míchal" }, { label: "Horní řada zleva", names: "Luboš Říha (trenér), Aleš Vojáček, Tomáš Medřický, Tomáš Janeček, Václav Havránek, Zdeněk Lebeda, Jakub Volter, Bohumil Čapek (trenér), Lukáš Říha" }, { label: "Prostřední řada zleva", names: "David Semerád, Radim Havelka, Vladimír Machka, František Francl, Václav Wolter, Marcel Sehnoutka, Lubor Steiner" }, { label: "Dolní řada zleva", names: "Lukáš Volf" }] },
  { season: "2012/2013", team: "Muži", file: "2012-2013_1_men.jpg", rowList: [{ label: "Horní řada zleva", names: "Vladimír Kupera ml., Václav Ronovský ml., Aleš Šulc, Jan Čapek, Stanislav Balvín, Marián Hodač, Robert Uhlíř, Václav Říha, Pavel Javůrek, Václav Ronovský, Jaroslav Doležal (trenér)" }, { label: "Prostřední řada zleva", names: "Jakub Ronovský, Ondřej Čapek, Lukáš Dvořák, Vlastimil Růžička, Radek Prášek, Karel Mikeš" }, { label: "Dolní řada zleva", names: "Jan Vaněk, David Míchal" }, { label: "Horní řada zleva", names: "Jakub Ronovský, Aleš Kotrba, Jan Čapek, Petr Marousek, Václav Ronovský ml., Radek Prášek, Vlastimil Růžička, Robert Uhlíř, Jaroslav Doležal (trenér), David Míchal" }, { label: "Dolní řada zleva", names: "Jakub Havránek, Václav Žaloudek, Jan Vaněk, Ondřej Čapek, Lukáš Dvořák, Václav Říha, Stanislav Balvín" }, { label: "Horní řada zleva", names: "Jakub Ronovský, Jaroslav Doležal (trenér), Jan Čapek, Petr Marousek, Václav Ronovský ml., Vladimír Kupera ml., Robert Uhlíř, Radek Novotný, Stanislav Balvín" }, { label: "Dolní řada zleva", names: "Václav Říha, Jakub Havránek, Ondřej Čapek, Aleš Kotrba, Radek Prášek, Jan Vaněk, Lukáš Dvořák, Václav Žaloudek, Vlastimil Růžička" }, { label: "Horní řada zleva", names: "pan Volter, Zdeněk Lebeda, Tomáš Medřický, Václav Havránek, Radim Havelka, David Semerád, Tomáš Janeček, Aleš Vojáček, Marcel Sehnoutka, Lukáš Říha, Luboš Říha (trenér)" }, { label: "Prostřední řada zleva", names: "Jakub Volter, Vladimír Machka, František Francl, Václav Volter, Martin Medřický" }, { label: "Dolní řada zleva", names: "Lukáš Volf, Petr Samek" }, { label: "Horní řada zleva", names: "Lukáš Říha, Zdeněk Lebeda, Lukáš Volf, Tomáš Janeček, Aleš Vojáček, Lubor Steiner, Jakub Volter, Luboš Říha (trenér)" }, { label: "Prostřední řada zleva", names: "Václav Volter, František Francl, Vladimír Machka, Radim Havelka, David Semerád, Petr Malý" }, { label: "Dolní řada zleva", names: "Marcel Sehnoutka" }] },
  { season: "2013/2014", team: "Muži", file: "2013-2014_1_men.jpg", rowList: [{ label: "Horní řada zleva", names: "Vlastimil Růžička, David Vondráček, Jan Čapek, Jakub Havránek, Robert Uhlíř, Aleš Šulc, Jan Vaněk, Petr Marousek, Václav Ronovský, Jakub Ronovský, Václav Říha, Jaroslav Doležal (trenér)" }, { label: "Dolní řada zleva", names: "Martin Kaňka, Milan Urválek, Ondřej Čapek, Josef Fendrych, Radek Novotný, Lukáš Dvořák, Vladimír Kupera" }] },
  { season: "2014/2015", team: "Muži", file: "2014-2015_1_men.jpg", rowList: [{ label: "Horní řada zleva", names: "Lubomír Říha, Petra Zajícová, Jakub Ronovský, Aleš Kotrba, Miroslav Hašek, Petr Marousek, Václav Ronovský, Tomáš Doležal, Jan Čapek, Václav Říha, Jaroslav Doležal (trenér)" }, { label: "Dolní řada zleva", names: "Ondřej Čapek, Zdeněk Daru, Lukáš Dvořák, Aleš Zelený, Adam Vondrák, Martin Kaňka, Vlastimil Růžička" }, { label: "Horní řada zleva", names: "Jaroslav Doležal (trenér), Jan Čapek, Vladimír Kupera, Jan Vaněk, Radek Prášek, Václav Říha, Robert Uhlíř, Tomáš Doležal, Miroslav Hašek, David Vondráček, Luboš Říha, Jakub Ronovský" }, { label: "Dolní řada zleva", names: "Martin Kaňka, Ondřej Čapek, Václav Ronovský, Lukáš Dvořák, Vlastimil Růžička, Libor Milaberský, Zdeněk Daru" }, { label: "Horní řada zleva", names: "Václav Ronovský ml. (trenér), Lukáš Zajíc, Vlastimil Růžička, Miroslav Voplakal, Karel Šindelka, Aleš Šulc, Stanislav Balvín, Karel Čubr, David Steiner, Jaroslav Doležal (předseda), Lubomír Říha (místopředseda)" }, { label: "Prostřední řada zleva", names: "Ivan Babák, Zdeněk Novotný, Václav Prášek, Aleš Kotrba, Vladimír Kupera, Milan Dalešický, Jan Burian" }, { label: "Dolní řada zleva", names: "Petr Dostál, Matyáš Kotrba (zdravotník)" }] },
  { season: "2015/2016", team: "Muži", file: "2015-2016_1_men.jpg", rowList: [{ label: "Horní řada zleva", names: "Lubomír Říha (místopředseda), Lukáš Říha, Robert Uhlíř, Tomáš Doležal, Aleš Kotrba, Pavel Javůrek, Jakub Ronovský, Radek Prášek, Zdeněk Daru, Jaroslav Doležal (trenér)" }, { label: "Prostřední řada zleva", names: "Lukáš Dvořák, Václav Ronovský, Ondřej Čapek, Martin Kaňka, Libor Milaberský, Vlastimil Růžička, Václav Říha, Matyáš Kotrba (zdravotník)" }, { label: "Dolní řada zleva", names: "Martin Tyrkas" }, { label: "Horní řada zleva", names: "Lubomír Říha (místopředseda), Václav Ronovský, Jakub Ronovský, Tomáš Doležal, Petr Marousek, Aleš Kotrba, Jan Čapek, Robert Uhlíř, Vladimír Kupera, Pavel Javůrek, Jaroslav Doležal (trenér)" }, { label: "Dolní řada zleva", names: "Radek Prášek, Ondřej Čapek, Vlastimil Růžička, Lukáš Pulkert, Libor Milaberský, Martin Kaňka, Milan Urválek, Václav Říha" }] },
  { season: "2016/2017", team: "Muži", file: "2016-2017_1_men.jpg", rowList: [{ label: "Horní řada zleva", names: "Andrea Kotrbová, Václav Ronovský ml., Pavel Javůrek, Jakub Ronovský, Robert Uhlíř, Vladimír Kupera, Tomáš Doležal, Jan Čapek, Petra Zajícová, Jaroslav Doležal (trenér)" }, { label: "Prostřední řada zleva", names: "Roman Prášek, Ondřej Čapek, Martin Kaňka, Milan Urválek, Aleš Kotrba, Václav Říha" }, { label: "Dolní řada zleva", names: "David Míchal" }, { label: "Horní řada zleva", names: "Andrea Kotrbová, Tomáš Doležal, Vladimír Kupera, Jakub Ronovský, Robert Uhlíř, Václav Ronovský ml., Radek Prášek, Pavel Javůrek, Jan Čapek, Jaroslav Doležal (trenér)" }, { label: "Prostřední řada zleva", names: "Ondřej Kamrád, Milan Urválek, Ondřej Čapek, Martin Kaňka, Libor Milaberský, Václav Říha" }, { label: "Dolní řada zleva", names: "Lukáš Volf, David Míchal" }] },
  { season: "2017/2018", team: "Muži", file: "2017-2018_1_men.jpg", rowList: [{ label: "Horní řada zleva", names: "Tomáš Doležal, Štěpán Bochníček, Václav Ronovský ml., Jan Čapek, Vladimír Kupera, Petr Marousek, Aleš Kotrba, Jakub Ronovský, Václav Říha, David Míchal, Jaroslav Doležal (trenér)" }, { label: "Prostřední řada zleva", names: "Lukáš Volf, Vlastimil Růžička, Robert Uhlíř, Matyáš Kotrba (zdravotník), Martin Kaňka, Lukáš Říha, Milan Urválek, Ondřej Čapek" }, { label: "Dolní řada zleva", names: "Petr Votruba" }, { label: "Horní řada zleva", names: "Aleš Kotrba, Petra Zajícová, Andrea Kotrbová, Václav Ronovský ml., Petr Marousek, Tomáš Doležal, Jakub Ronovský, Jan Čapek, Radek Prášek, Vlastimil Růžička, Jaroslav Doležal (trenér)" }, { label: "Prostřední řada zleva", names: "Matyáš Kotrba, Milan Urválek, Petr Malý, Martin Kaňka, Štěpán Bochníček, Václav Říha, Ondřej Čapek" }, { label: "Dolní řada zleva", names: "Lukáš Volf, Petr Votruba" }] },
  { season: "2018/2019", team: "Muži", file: "2018-2019_1_men.jpg", rowList: [{ label: "Horní řada zleva", names: "Lubomír Říha (místopředseda), Andrea Kotrbová, Vladimír Kupera, Tomáš Doležal, Robert Uhlíř, Petr Marousek, Martin Vondráček, Petr Karlík, Aleš Kotrba, Jaroslav Doležal (trenér), Petra Zajícová" }, { label: "Prostřední řada zleva", names: "Pavel Javůrek, Ondřej Čapek, Roman Prášek, Jan Čapek, Milan Urválek, Libor Milaberský, Martin Kaňka, Václav Říha" }, { label: "Dolní řada zleva", names: "Petr Votruba, David Míchal" }, { label: "Horní řada zleva", names: "Lubomír Říha (místopředseda), Tomáš Doležal, Robert Uhlíř, Martin Vondráček, Jan Čapek, Petr Marousek, Jakub Ronovský, Pavel Javůrek, Andrea Kotrbová, Jaroslav Doležal (trenér)" }, { label: "Prostřední řada zleva", names: "Antonín Vrdský, Roman Prášek, Lukáš Říha, Ondřej Čapek, Martin Kaňka, Václav Říha, David Míchal" }, { label: "Dolní řada zleva", names: "Petr Votruba" }] },
  { season: "2019/2020", team: "Muži", file: "2019-2020_1_men.jpg", rowList: [{ label: "Horní řada zleva", names: "Antonín Vrdský, Andrea Kotrbová, Ondřej Čapek, Tomáš Doležal, Jan Čapek, Petr Karlík, Martin Vondráček, Václav Ronovský, Petr Marousek, Aleš Kotrba, Jaroslav Doležal (trenér), Lubomír Říha (místopředseda)" }, { label: "Dolní řada zleva", names: "Robert Uhlíř, Jakub Ronovský, Petr Votruba, Martin Kaňka, Jakub Čech, Václav Říha" }] },
  { season: "2020/2021", team: "Muži", file: "2020-2021_1_men.jpg", rowList: [{ label: "Horní řada zleva", names: "Matyáš Kotrba, Yevhen Pavlenko, Tomáš Doležal, Robert Uhlíř, Jakub Čech, Antonín Vrdský, Petr Karlík, Pavel Javůrek, Jakub Ronovský, Martin Vondráček, Petr Marousek, Jaroslav Doležal (trenér)" }, { label: "Dolní řada zleva", names: "Petr Votruba, Václav Říha, Ondřej Čapek, Martin Kaňka, Roman Lytvynenko, Roman Kurochkin, Roman Prášek" }] },
  { season: "2021/2022", team: "Muži", file: "2021-2022_1_men.jpg", rowList: [{ label: "Horní řada zleva", names: "Lubomír Říha (místopředseda), Robert Uhlíř, Petr Karlík, Jakub Ronovský, Petr Marousek, Petr Votruba, Václav Ronovský, Oleh Hvozdyk, Václav Říha, Jaroslav Doležal (trenér)" }, { label: "Prostřední řada zleva", names: "Ondřej Čapek, Martin Kaňka, Martin Dvořák, Jakub Škodák, Roman Lytvynenko" }, { label: "Dolní řada zleva", names: "Tomáš Skokan" }, { label: "Horní řada zleva", names: "Petr Votruba, Oleh Hvozdyk, Robert Uhlíř, Dmytro Protsenko, Petr Klička, Aleš Kotrba, Petr Karlík, Petr Marousek, Libor Petříček, Tomáš Skokan, Jaroslav Doležal (trenér)" }, { label: "Dolní řada zleva", names: "Josef Kovář, Martin Kaňka, Jan Štěpař, Jakub Čech, Václav Říha, Martin Dvořák, Jakub Škodák, Roman Lytvynenko, Ondřej Čapek" }] },
  { season: "2022/2023", team: "Muži", file: "2022-2023_1_men.jpg", rowList: [{ label: "Horní řada zleva", names: "Aleš Kotrba, Oleh Hvozdyk, Roman Lytvynenko, Petr Marousek, Milan Běhounek, Petr Karlík, Jan Štěpař, Pavel Javůrek, Jakub Čech, Jaroslav Doležal (trenér)" }, { label: "Prostřední řada zleva", names: "Ondřej Čapek, Matyáš Kotrba, Martin Kaňka, David Prchal, Petr Malý, Josef Kovář, Václav Říha" }, { label: "Dolní řada zleva", names: "Petr Votruba, Tomáš Trunek" }, { label: "Horní řada zleva", names: "Jaroslav Doležal (trenér), Jiří Šikal, Oleh Hvozdyk, Antonín Vrdský, Petr Marousek, Jan Štěpař, Václav Říha, David Prchal, Petr Votruba, Aleš Kotrba" }, { label: "Dolní řada zleva", names: "Josef Kovář, Matyáš Kotrba, Martin Dvořák, Ondřej Čapek, Roman Lytvynenko, Jakub Škodák, Petr Klička" }] },
  { season: "2024/2025", team: "Muži", file: "2024-2025_1_men.jpg", rowList: [{ label: "Horní řada zleva", names: "Petr Votruba, Roman Lytvynenko, David Prchal, Petr Marousek, Vladyslav Shylo, Jan Štěpař, Oleh Hvozdyk, Matyáš Kotrba, Jaroslav Doležal (trenér), Martin Kaňka, Jan Tichý" }, { label: "Dolní řada zleva", names: "Petr Votruba ml., Jiří Šikal, Oleksandr Shpuryk, Artem Doroschenko, Václav Říha, Milan Běhounek, Jakub Čech, Ondřej Čapek" }] },
  { season: "2025/2026", team: "Muži", file: "2025-2026_1_men.jpg", rowList: [{ label: "Horní řada zleva", names: "Jan Štěpař, Petr Marousek, Petr Votruba ml., Oleg Hvozdyk, Josef Kovář, Petr Votruba, Marek Magat, Jakub Čech, David Prchal, Artem Doroschenko, Jaroslav Doležal (trenér)" }, { label: "Dolní řada zleva", names: "Ondřej Čapek, Václav Říha, Martin Kaňka, Vladyslav Shylo, Matyáš Kotrba, Jan Tichý, Roman Lytvynenko, Filip Štěpař" }] },
];

export { TEAM_PHOTOS };
export default TEAM_PHOTOS;
